version: '3'

services:
  web:
    build: .
    container_name: deno-container
    image: deno-image
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: mongod --port 5000
    ports:
      - '5000:5000'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: